JM-7256: Internal server error when selecting juror number link from appearance table
hmcts/juror-bureau pull request #363
Opened 2024-05-16 15:14 UTC by annemariesteenkamp

### JIRA link (if applicable) ###
https://centralgovernmentcgi.atlassian.net/browse/JM-7256

### Change description ###
Fix to enable juror number link to work properly

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-05-16 15:56 UTC, ricardofreitasrocha approved these changes

2024-05-16 15:56 UTC, ricardofreitasrocha commented on server/routes/juror-management/juror-record/juror-record.controller.js
> +        req.session.authentication.locCode = req.query.loc_code;
we should not mutate this... it is the data that gets decoded from the token 🙃  and changing it will break the app in other places....

2024-05-16 15:57 UTC, ricardofreitasrocha requested changes

2024-05-16 15:57 UTC, ricardofreitasrocha commented on server/routes/juror-management/juror-record/juror-record.controller.js
> +        req.session.authentication.locCode = req.query.loc_code;
...

2024-05-24 14:05 UTC, ricardofreitasrocha approved these changes

2024-05-28 08:47 UTC, callum-r-young approved these changes

2024-05-28 08:53 UTC, merged