Changed signature to firstname and last name
hmcts/juror-bureau pull request #533
Opened 2024-06-13 10:34 UTC by Roonneeyy

### JIRA link (if applicable) ###
https://centralgovernmentcgi.atlassian.net/browse/JM-7138

### Change description ###
Changed the letter generator footer to use first and last name rather than signature

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-06-14 11:15 UTC, ricardofreitasrocha requested changes

2024-06-14 11:15 UTC, ricardofreitasrocha commented on server/routes/documents/pdf/letter-generator.js
> +          signature: `${data.firstName} ${data.lastName}`,
the signature is a string that we should get from the api that reads as `The jury officer` or `The court manager`... the `footerText` property is what sets the name of the officer printing the letter, which should also be driven by the api response....

2024-06-14 11:17 UTC, ricardofreitasrocha commented on server/routes/documents/pdf/letter-generator.js
> +          signature: `${data.firstName} ${data.lastName}`,
so here:

![image](https://github.com/hmcts/juror-bureau/assets/140706972/22c87694-e0e5-42e5-b956-23f8f6b0ee31)

`Court Manager` would be the name of the officer, that is set in the `footerText: ` property and `Jury Manager` would be the actual signature that we get from the api.

2024-06-19 11:24 UTC, akikrahman1 approved these changes

2024-06-19 11:30 UTC, ricardofreitasrocha approved these changes

2024-06-19 11:30 UTC, merged